image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [923.87896,   0.     , 642.04345,
           0.     , 923.93914, 389.05006,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.083369, -0.162970, -0.001878, 0.000352, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [926.42527,   0.     , 642.73006,   0.     ,
           0.     , 934.23109, 388.10721,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
